export const FETCHING_QUESTIONS_REQUEST = 'FETCHING_QUESTIONS_REQUEST'
export const FETCHING_QUESTIONS_SUCCESS = 'FETCHING_QUESTIONS_SUCCESS'
export const FETCHING_QUESTIONS_ERROR = 'FETCHING_QUESTIONS_ERROR'
export const CLEAR_QUESTIONS = 'CLEAR_QUESTIONS'

export const SAVE_ANSWER = 'SAVE_ANSWER'
export const CLEAR_ANSWER = 'CLEAR_ANSWER'
